Include "Cancelled" in Skipped Statuses
re-actors/alls-green pull request #7
Opened 2022-06-14 19:37 UTC by tubbo

Jobs can be cancelled externally, either manually or automatically with an action. Cancelled jobs fall into the "failure" state of this action, and since they are not explicit failures they should be considered as "skipped" in the same way that jobs which are automatically skipped are.

2022-06-14 19:58 UTC, tomparkp approved these changes

2022-07-22 21:25 UTC, webknjaz requested changes
Thanks for the contribution but I don't think this assumption is reasonable by default. This action usually shields from some dangerous side effects like making releases.
It is not explicitly demonstrated in the README snippet but a lot of this action's use looks as follows:

```mermaid
graph LR;
    T([Tests]) -- all's good? --> A([this action]);
    M([Metadata validation]) -- all's good? --> A([this action]);
    L([Linters]) -- all's good? --> A([this action]);
    A([this action]) -- is the action green? --> P([Publish to PyPI]);
    A([this action]) -- is the action green? --> H([Deploy to Heroku]);
    A([this action]) == is the action green? ==> B([Burn down the world]);
```

So with this, you're able to cancel a job that cascades into this action giving a green light to perform something destructive 🔥🌍.

Though, if you don't care about a job, why not just add it to `allowed-failures` and be done with it?

If you still think that you *really* need this, it's probably best to introduce a separate input called `allowed-cancels`.

2022-07-23 14:21 UTC, tubbo commented
@webknjaz We use this to prevent our publish job from running until all of the other jobs complete or are skipped, but that's basically just to prevent communicating a release update until the site is fully deployed. I guess we're using it differently than most others, since if a job is canceled then the publish job will be canceled as well. The problem was that this job considered canceled jobs to be failures, so we were getting a lot of spam in our notifications when the publish job "failed", but it was actually just being canceled. I don't feel like this is totally necessary for everyone, and hearing your reasoning on why this decision was made, it now makes a lot of sense why alls-green works this way out of the box. We're not using it to block a dangerous job from running until all others have passed, so I think I'll close this and we can continue using our fork for the time being.

2022-07-23 14:22 UTC, closed without merging

2022-07-25 23:33 UTC, webknjaz commented
FWIW, I'm totally open to having a separate input for this. It just needs to come with a fair warning in the README :)